### ISSUE TITLE
Reply already submitted

### ISSUE THREAD

**Issue by davidstoneham** [once10301/wifi#21]
Happens after restarting the application when debugging.
```
E/MethodChannel#plugins.ly.com/wifi(29681): Failed to handle method call

E/MethodChannel#plugins.ly.com/wifi(29681): java.lang.IllegalStateException: Reply already submitted

E/MethodChannel#plugins.ly.com/wifi(29681): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:209)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.ly.wifi.WifiDelegate.finishWithError(WifiDelegate.java:267)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.ly.wifi.WifiDelegate.finishWithAlreadyActiveError(WifiDelegate.java:263)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.ly.wifi.WifiDelegate.getWifiList(WifiDelegate.java:136)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.ly.wifi.WifiPlugin.onMethodCall(WifiPlugin.java:44)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at android.os.MessageQueue.nativePollOnce(Native Method)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at android.os.MessageQueue.next(MessageQueue.java:326)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at android.os.Looper.loop(Looper.java:160)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at android.app.ActivityThread.main(ActivityThread.java:6718)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at java.lang.reflect.Method.invoke(Native Method)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)

E/MethodChannel#plugins.ly.com/wifi(29681): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by ghost** [comment]
having Same issue. Will it work for released apk?
