### ISSUE TITLE
Android app crashes after permission request popup

### ISSUE THREAD

**Issue by ViniciusDS** [once10301/wifi#38]
Android app crashes first time request permission when launching, on both deny and grant action. The app restarts, it works fine then.

E/AndroidRuntime(11564): FATAL EXCEPTION: main
E/AndroidRuntime(11564): Process: br.com.etereo.app, PID: 11564
E/AndroidRuntime(11564): java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {br.com.etereo.app/br.com.etereo.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.flutter.plugin.common.MethodCall.argument(java.lang.String)' on a null object reference
E/AndroidRuntime(11564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
E/AndroidRuntime(11564): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
E/AndroidRuntime(11564): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(11564): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(11564): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(11564): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
E/AndroidRuntime(11564): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(11564): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(11564): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(11564): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11564): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(11564): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(11564): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object io.flutter.plugin.common.MethodCall.argument(java.lang.String)' on a null object reference
E/AndroidRuntime(11564): 	at com.ly.wifi.WifiDelegate.launchWifiList(WifiDelegate.java:180)
E/AndroidRuntime(11564): 	at com.ly.wifi.WifiDelegate.onRequestPermissionsResult(WifiDelegate.java:300)
E/AndroidRuntime(11564): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
E/AndroidRuntime(11564): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
E/AndroidRuntime(11564): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
E/AndroidRuntime(11564): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:611)
E/AndroidRuntime(11564): 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8262)
E/AndroidRuntime(11564): 	at android.app.Activity.dispatchActivityResult(Activity.java:8112)
E/AndroidRuntime(11564): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
E/AndroidRuntime(11564): 	... 11 more
I/Process (11564): Sending signal. PID: 11564 SIG: 9

wifi 0.1.5
Android 10

**Comment by McSam94** [comment]
Any update on this matter? I'm having the same issue

**Comment by ViniciusDS** [comment]
I solved as follows:
I installed the plugin: permission_handler and request permission before entering the page where I use wifi.
